### ISSUE TITLE
[Help needed] won't work with T7 2TB shield

### ISSUE THREAD

**Issue by xila76** [rsenden/t3unlock#4]
I recently purchased a T7 shield 2TB, and set encryption from a MBP M1 (arm).
I try to access to this portable ssd from a Linux Mint laptop too.

Can you please help me to adapt for T7 ?

I've changed productId for matching with what i can see with a "lsbusb" command

ProductID for T7 shield is : 
`productId = 0x61fc;`

The command :
`sudo java -jar target/T3Unlock-1.0.jar SECRETPASSWORD`

Output :
```
LibUsb.init
Find Device: 1256:25084
Open Device
Detach kernel driver
Claiming interface
Host->Device (length=31, endpoint=2): [85, 83, 66, 67, 10, 0, 0, 0, 0, 2, 0, 0, 0, 0, 16, -123, 10, 38, 0, -42, 0, 1, 0, -42, 0, 79, 0, -62, 0, -80, 0]
31 bytes sent
Host->Device (length=512, endpoint=2): [98, 115, 117, 121, 103, 118, 104, 90, 56, 57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
512 bytes sent
org.usb4java.LibUsbException: USB error 7: Unable to read data: Operation timed out
	at io.github.rsenden.t3.unlock.T3Unlock$UsbHelper.bulkTransferReadFromDevice(T3Unlock.java:119)
	at io.github.rsenden.t3.unlock.T3Unlock.main(T3Unlock.java:38)

```

Maybe if someone can translate this projet into python, it will be more easy for me to debug what happen :crossed_fingers: 
Or if @vingarzan @rsenden can specify to us how they intercept vendor specific commands ? (with wireshark and usb capture?)

Thanks a lot to all readers and helpers

**Comment by rsenden** [comment]
Hi, to start with, it might be dangerous to run this on a drive model/firmware with which the utility hasn't been tested, as potentially the commands being sent to the drive have a different meaning compared to the model/firmware that I initially developed this for.

Having said that, when I developed this, I think I used the official Windows unlock utility and monitored USB traffic to see what commands were being sent when unlocking the drive. I may also have had a look at the Android classes to see what commands they were sending. Unfortunately it is too long ago to remember exactly how I eventually found out the correct commands.

I hardly use USB drives anymore, so I'm no longer actively using this utility. Of course, being open source, anyone is free to fork the repository and continue development.
